version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run:
          name: "set keys"
          command: |
            sed 's/YOUR_YELP_DEVELOPER_KEY/'"${yelpBearerKey}"'/g' ./Yelp.postman_environment.json > ./temp_Yelp.postman_environment.json
      - newman/newman-run:
            collection: ./test_suites/Yelp_V3_e2e_test.postman_collection.json
            environment: ./temp_Yelp.postman_environment.json