version: 2
jobs:
  build:
    docker:
      - image: postman/newman:4.4.1
    steps:
      - checkout
      - run:
          name: set keys
          command: |
            sed 's/YOUR_YELP_DEVELOPER_KEY/'"${yelpBearerKey}"'/g' ./Yelp.postman_environment.json > ./temp_Yelp.postman_environment.json
      - run:
          command: "newman run ./test_suites/Yelp_V3_e2e_test.postman_collection.json\
          \ --environment ./temp_Yelp.postman_environment.json              \n"
  nightly:
    triggers: #use the triggers key to indicate a scheduled build
      - schedule:
          cron: "0 43 * * *" # use cron syntax to set the schedule
          filters:
            branches:
              only:
                - master
