version: 2
jobs:
  build:
    docker:
      - image: postman/newman:4.4.1
    steps:
      - checkout
      - run:
          name: set keys
          command: |
            sed 's/YOUR_YELP_DEVELOPER_KEY/'"${yelpBearerKey}"'/g' ./Yelp.postman_environment.json > ./temp_Yelp.postman_environment.json
      - run:
          command: "newman run ./test_suites/Yelp_V3_e2e_test.postman_collection.json\
          \ --environment ./temp_Yelp.postman_environment.json              \n"
workflows:
  version: 2
  workflow:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "52 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
